### ISSUE TITLE
Update to latest version?

### ISSUE THREAD

**Issue by jwortmann** [facelessuser/sublime-coloraide#1]
I saw that you just made a 1.0 release for coloraide, which is pretty cool, and I wondered if that would be a good opportunity to update the ST dependency to this version?

I realized that Package Control doesn't have any versioning system for dependencies, and also there isn't really a feasible way to find out which packages use a particular dependency. That might be the reason why a lot of dependencies are stuck at ancient version and seem to be abandoned. But in the case of coloraide, I might be the only other user of it in https://github.com/jwortmann/quick-view (can't say for sure, of course). Currently, I only use `Color.match` and `Color.convert` (and I wouldn't want to miss it), but I'd like to have a look if I can make use of color interpolation in the future, if the dependency got updated.

**Comment by facelessuser** [comment]
Yep, that is actually my plan. I've avoided updating it because we weren't to this point.

**Comment by facelessuser** [comment]
Tagged
